language: python
python:
  - "3.12"
  - "3.13"
  - "3.14"
install:
  - pip install pdm
  - pdm install
script:
  - pdm run pytest
jobs:
  include:
    - stage: GitHub 
      if: branch = master
      script: echo "Deploying to GitHub releases ..."
      deploy:
        script: skip
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: dist/*
        skip_cleanup: true
        on:
          tags: true
