name: Test Coveralls

on: ["push", "pull_request"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.6
