name: Test Coveralls

on: ["push", "pull_request"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4

    - name: Install dependencies
      run: |
        pdm install
        pdm pip install types-lxml
        pdm pip install coveralls

    - name: Run tests
      run: |
        coverage run --source=pudding -m pytest tests/
        coveralls
