# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
    - name: Install dependencies
      run: pdm install
    - name: Check linting
      continue-on-error: true
      run: pdm lint
    - name: Check typing
      continue-on-error: true
      run: pdm typing --install-types --non-interactive
    - name: Run tests
      run: pdm test
